name: core
description: A new Flutter package project.
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  dartz: ^0.9.2
  equatable: ^1.2.5
  flutter_cache_manager: ^2.1.1
  data_connection_checker: ^0.3.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
